# Generated by Django 4.1.5 on 2023-01-31 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageServer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
