# Generated by Django 4.1.6 on 2023-02-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageServer', '0004_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='title',
        ),
    ]
